### ISSUE TITLE
Tree-NeighborsMatch problem

### ISSUE THREAD

**Issue by Barcavin** [tech-srl/bottleneck#6]
Hi,

This is an interesting paper. may find some fundamental issues about GNN.

I have a question about the Tree-NeighborsMatch problem. In my understanding, 1-layer GNN can pretty much solve it, because what the model has to do is:
1. let all the green nodes, including both the target node and labelled leaves nodes, count the number of neighbors they have.
2. Let the classifier at the final layer figure out 2 neighbors means to label "C". then it should label the target node as "C" given that it has 2 neighbors.

In this case, it doesn't have to message pass all the information from leaves nodes to target nodes to find out the most similar one. It doesn't need to "match", it just needs to learn 2 --> "C"

**Comment by urialon** [comment]
Hi @Barcavin ,
Thank you for your interest in our paper and for your kind words!

The dataset has many examples, where every example is a different graph with a different mapping between numbers (such as 2) and labels (such as "C").
So, in one graph, 2 blue neighbors should be classified as "C", but in another graph, 2 neighbors should be classified as "D".
Since this mapping is different in every graph, the GNN needs to pass all the information from the leaf nodes to the target node, in every graph.

does it make more sense now?
Feel free to ask if you have additional questions.

**Comment by Barcavin** [comment]
That makes sense now. Thanks for your explanations!
